numbers = [1,2,3,4,5]
numbers.append(6)
print(numbers)
numbers.insert(0, -1)
print(numbers)
numbers.remove(3)
print(numbers)
numbers.insert(len(numbers),3)
print(numbers)
x = 2
print(x in numbers)
print(1 in numbers)
print(15 in numbers)
numbers.clear()
print(numbers)
